### ISSUE TITLE
OAuth branch doesn't gracefully handle user cancel at permissions prompt

### ISSUE THREAD

**Issue by callahad** [mozilla/persona-gmail-bridge#127]
1. Make sure that you have not authorized the bridge to access your account: https://security.google.com/settings/u/0/security/permissions?pli=1
2. Attempt to sign into an RP
3. When you see the permissions prompt, click "Cancel"

You end up back on `/authenticate/verify?error=access_denied&state=...` with a generic error message:

![screen shot 2015-02-10 at 15 02 25](https://cloud.githubusercontent.com/assets/24193/6136380/e0469c74-b135-11e4-8ae4-68d8e64124eb.png)

Instead, you should be taken back to the picker.

Clicking "Cancel" does return you to the picker as expected.

**Comment by callahad** [comment]
We can fix this by inserting a test and early return at [the top of that route's handler](https://github.com/mozilla/persona-gmail-bridge/blob/7d9b0be123cc9ca72c06677e7114dddeacf93929/bin/persona-gmail-bridge.js#L264):

``` diff
diff --git a/bin/persona-gmail-bridge.js b/bin/persona-gmail-bridge.js
index 0e63494..2996664 100755
--- a/bin/persona-gmail-bridge.js
+++ b/bin/persona-gmail-bridge.js
@@ -262,6 +262,15 @@ app.get('/authenticate/forward', validate({ email: 'gmail' }),


 app.get('/authenticate/verify', function (req, res) {
+  // Fail early if the user hit cancel in the OAuth dialog
+  // Though, access denied? Are we somehow not detecting cancellation up front?
+  if (req.query.error && req.query.error === 'access_denied') {
+      logger.info('User cancelled during oauth dialog');
+      statsd.increment('authentication.oauth.failure.cancelled');
+      return res.render('authenticate_finish',
+        { title: req.gettext('Loading...'), success: false });
+  }
+
   // Check input precondition:
   // The bridge should return the expected state token.
   if (! (req.query.state &&
```

However, the handler *does* have code that [looks like it wants to handle cancellations](https://github.com/mozilla/persona-gmail-bridge/blob/7d9b0be123cc9ca72c06677e7114dddeacf93929/bin/persona-gmail-bridge.js#L296-L300). Is that dead code? Incorrect code? Investigating...

**Comment by callahad** [comment]
This looks like the correct solution.

Hitting cancel directly 302's from Google to `/authenticate/verify?error=access_denied`, so we need to handle it there.

![screen shot 2015-02-10 at 15 40 13](https://cloud.githubusercontent.com/assets/24193/6137029/3f138c08-b13b-11e4-9516-2cff8e9c0c73.png)

**Comment by shane-tomlinson** [comment]
Dan and I came up with the same solution outlined in https://github.com/mozilla/persona-gmail-bridge/issues/127#issuecomment-73788421, independently.

r=shane-tomlinson.

**Comment by shane-tomlinson** [comment]
@callahad - on second thought, I'd move the error check just below the state token check to avoid CSRF issues.

**Comment by callahad** [comment]
Fixed in feature branch, closing.
