### ISSUE TITLE
OAuth branch improperly hints addresses in format foo+bar@gmail.com

### ISSUE THREAD

**Issue by callahad** [mozilla/persona-gmail-bridge#128]
Google's OAuth endpoint ignores `login_hint` if the email address local part contains something like `+foo`.

STR:

1. Sign into Google as foo@gmail.com, then add an account and sign in as bar@gmail.com
2. Attempt to use Persona as foo+blah@gmail.com
3. Note the unhinted picker:

![screen shot 2015-02-10 at 15 09 43](https://cloud.githubusercontent.com/assets/24193/6136534/f562f5f2-b136-11e4-92ec-ae41126f293c.png)

If we strip the `+` suffix from addresses, the `login_hint` works properly and prompts for the correct account.

**Comment by callahad** [comment]
This can be fixed by exposing and using the preexisting `canonicalized` function in our email lib.

``` diff
diff --git a/lib/email.js b/lib/email.js
index 03c67d8..c53f37d 100644
--- a/lib/email.js
+++ b/lib/email.js
@@ -64,6 +64,7 @@ function isGmail(email) {
   return valid(email) && !!canonicalized(email);
 }

+exports.canonicalized = canonicalized;
 exports.compare = compare;
 exports.valid = valid;
 exports.isGmail = isGmail;
diff --git a/lib/google.js b/lib/google.js
index a679cdc..4003239 100644
--- a/lib/google.js
+++ b/lib/google.js
@@ -3,6 +3,7 @@
  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

 const config = require('../lib/config');
+const canonicalized = require('../lib/email').canonicalized;

 const CLIENT_ID = config.get('google.clientId');
 const CLIENT_SECRET = config.get('google.clientSecret');
@@ -53,7 +54,7 @@ module.exports = {
   getAuthUrl: function (email, state, callback) {
     /*jshint camelcase: false*/
     var options = {
-      login_hint: email,
+      login_hint: canonicalized(email),
       access_type: 'online',
       scope: SCOPE,
       state: state,
```

@shane-tomlinson r?

**Comment by callahad** [comment]
The only risk is that an invalid email gets passed to `getAuthUrl`, but [we have a guard in place for that](https://github.com/mozilla/persona-gmail-bridge/blob/7d9b0be123cc9ca72c06677e7114dddeacf93929/bin/persona-gmail-bridge.js#L234).

In the worst case, `login_hint` would get set to `NaN`, which Google ignores, presenting the user with an unhinted picker. Which is totally fine, since that's all we had in the OpenID 2.0 world anyways ;)

**Comment by shane-tomlinson** [comment]
@callahad - LGTM, I tried an email address with "+1". I went to google, authenticated sans "+1", returned to Persona and the assertion was generated with the "+1".

**Comment by shane-tomlinson** [comment]
For https://github.com/mozilla/persona-gmail-bridge/issues/128#issuecomment-73787115

r=shane-tomlinson

**Comment by callahad** [comment]
Since you asked in IRC, the +1 reappears because:

1. In `/authenticate/forward`, before we send the user to Google, [we stash their claimed email](https://github.com/mozilla/persona-gmail-bridge/blob/7d9b0be123cc9ca72c06677e7114dddeacf93929/bin/persona-gmail-bridge.js#L255), exactly as they typed it, in `req.session.claimed`
2. When they come back from Google to `/authenticate/verify`, if successful, [we stash *google's* version of their email](https://github.com/mozilla/persona-gmail-bridge/blob/7d9b0be123cc9ca72c06677e7114dddeacf93929/bin/persona-gmail-bridge.js#L311), which may have different dots or whatnot, in `req.session.proven`.
3. Then, before we actually issue a cert, we compare the claimed to proven addresses with `email.compare(claimed, proven)`, which [normalizes both addresses](https://github.com/mozilla/persona-gmail-bridge/blob/7d9b0be123cc9ca72c06677e7114dddeacf93929/lib/email.js#L51-L61): stripping dots, +-affixes, etc.
4. If the comparison succeeds, [we sign the user's claimed address](https://github.com/mozilla/persona-gmail-bridge/blob/7d9b0be123cc9ca72c06677e7114dddeacf93929/bin/persona-gmail-bridge.js#L214), as they typed it.

**Comment by callahad** [comment]
Fixed in feature branch, closing.
