### ISSUE TITLE
Google OAuth consent screen too small to fit inside Persona popup

### ISSUE THREAD

**Issue by callahad** [mozilla/persona-gmail-bridge#129]
The first time you hit the OAuth permissions screen, it looks like this:

![screen shot 2015-02-10 at 14 42 52](https://cloud.githubusercontent.com/assets/24193/6136551/2895cb02-b137-11e4-827a-3f136aec0237.png)

Note that you can't see the Cancel or Allow buttons, and thanks to modern OS design, you often don't have any indication that you can scroll.

Here's what's missing:

![screen shot 2015-02-10 at 15 02 13](https://cloud.githubusercontent.com/assets/24193/6136560/454c717e-b137-11e4-8b3d-9f7d1f4c69f2.png)

**Comment by shane-tomlinson** [comment]
I have no logos, here is what I see:

![screen shot 2015-02-10 at 20 41 40](https://cloud.githubusercontent.com/assets/848085/6136621/277da2f2-b16a-11e4-9562-3a0fc83dcd5f.png)

If the user is unauthenticated, here is what they see:
![screen shot 2015-02-10 at 21 18 35](https://cloud.githubusercontent.com/assets/848085/6136661/782caaae-b16a-11e4-9213-1e4dd0f0b83e.png)

**Comment by callahad** [comment]
Yep, confirming that things look fine (and fit) without the logo. Closing.
